apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: gardening_db
  MYSQL_USER: gardenuser
  MYSQL_PASSWORD: gardenpass
